version: "2"
networks:
  react:
    name: react
services:
  nginx-react:
    restart : on-failure
    container_name: ngixreactapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    network:
      - react
    volumes : 
        - ./node_modules
        - .:/app
    environment:
      NODE_ENV: production
